import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

export default function TermsAndConditions() {
  return (
    <div className="min-h-screen bg-transparent flex flex-col max-w-md mx-auto relative overflow-hidden">
      <div className="flex-1 overflow-y-auto p-6 bg-[#fff8ea]/90 backdrop-blur-md m-4 my-4 rounded-3xl shadow-xl border border-amber-200/70">
        <Link to="/" className="inline-flex items-center gap-1 text-sm text-amber-700 hover:text-amber-900 mb-6">
          <ArrowLeft className="w-4 h-4" /> Back
        </Link>

        <h1 className="text-2xl font-serif text-stone-900 mb-2">Terms &amp; Conditions</h1>
        <p className="text-xs text-stone-500 mb-6">Last updated: June 2026</p>

        <div className="space-y-6 text-sm text-stone-700 leading-relaxed">

          <section>
            <h2 className="text-lg font-serif text-stone-900 mb-2">1. Acceptance of Terms</h2>
            <p>By creating an account or using Jyot, you agree to these Terms &amp; Conditions. If you do not agree, please do not use the application. Continued use of Jyot after any updates to these terms constitutes acceptance of the revised terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-serif text-stone-900 mb-2">2. Eligibility</h2>
            <p>You must be at least 13 years of age to use Jyot. By creating an account, you confirm that you are 13 years of age or older. If you are between 13 and 18 years old, you confirm that a parent or legal guardian has reviewed and agreed to these terms on your behalf.</p>
          </section>

          <section>
            <h2 className="text-lg font-serif text-stone-900 mb-2">3. Account Registration &amp; Security</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>You must provide accurate and complete information when registering.</li>
              <li>You are responsible for maintaining the confidentiality of your login credentials.</li>
              <li>You are responsible for all activity that occurs under your account.</li>
              <li>You must notify us immediately if you suspect unauthorized access to your account.</li>
              <li>We reserve the right to suspend or terminate accounts that violate these terms.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-serif text-stone-900 mb-2">4. User-Generated Content</h2>
            <p className="mb-2">Jyot allows you to create and store the following types of content:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>Wish titles and descriptions</strong> — stored on our servers and visible only to you.</li>
              <li><strong>Wish video recordings</strong> — stored locally on your device. See our Privacy Policy for details.</li>
              <li><strong>Jaap progress and spiritual goals</strong> — stored on our servers for your personal tracking.</li>
              <li><strong>Palm images</strong> — uploaded temporarily for AI analysis and not stored permanently.</li>
            </ul>
            <p className="mt-2">You retain full ownership of all content you create. Jyot does not claim any ownership over your wishes, recordings, or personal data.</p>
          </section>

          <section>
            <h2 className="text-lg font-serif text-stone-900 mb-2">5. Spiritual Guidance Disclaimer</h2>
            <div className="bg-amber-50 border-l-4 border-amber-500 p-4 rounded-r-xl mb-2">
              <p className="text-sm font-medium text-amber-900">Important: Jyot provides spiritual, cultural, educational, and entertainment-oriented guidance. It does not guarantee any prediction, outcome, result, or life event.</p>
            </div>
            <ul className="list-disc pl-5 space-y-1">
              <li>Palm readings are generated by AI (Google Gemini) for entertainment, reflection, and spiritual exploration purposes. They are not professional life, financial, medical, or psychological advice.</li>
              <li>Panchang and astrological information is provided for cultural and educational reference.</li>
              <li>Jaap tracking and spiritual goal features are motivational tools. No spiritual outcome, manifestation, or divine result is guaranteed.</li>
              <li>You should not make decisions about health, finances, relationships, or legal matters based on AI-generated readings or spiritual guidance provided through this app.</li>
              <li>If you are experiencing distress, we encourage you to seek support from qualified professionals.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-serif text-stone-900 mb-2">6. Prohibited Conduct</h2>
            <p className="mb-2">You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Use Jyot for any unlawful purpose or in violation of any applicable laws.</li>
              <li>Attempt to access another user's account, wishes, or personal data.</li>
              <li>Upload harmful content, malware, or abusive material.</li>
              <li>Use automated tools, bots, or scrapers to access or collect data from Jyot.</li>
              <li>Interfere with the operation of the application or its underlying infrastructure.</li>
              <li>Impersonate another person or entity.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-serif text-stone-900 mb-2">7. Subscriptions &amp; Payments</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>Jyot offers free and paid subscription plans. Paid plans are billed on the cycle selected during checkout.</li>
              <li>Subscription fees, if applicable, are non-refundable except as required by applicable law.</li>
              <li>We reserve the right to modify pricing with reasonable notice to existing subscribers.</li>
              <li>Payment processing is handled through third-party providers. Jyot does not store full payment card details on its servers.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-serif text-stone-900 mb-2">8. Limitation of Liability</h2>
            <div className="bg-stone-50 border-l-4 border-stone-400 p-4 rounded-r-xl mb-2">
              <p className="text-sm">To the maximum extent permitted by applicable law, Jyot and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or relating to your use of the application, including but not limited to loss of data, loss of locally stored wish videos, service interruptions, or reliance on AI-generated spiritual guidance.</p>
            </div>
            <p className="mt-2">Jyot is provided on an "as is" and "as available" basis without warranties of any kind, either express or implied.</p>
          </section>

          <section>
            <h2 className="text-lg font-serif text-stone-900 mb-2">9. Data Loss</h2>
            <p>Wish video recordings are stored locally on your device in browser-specific storage (IndexedDB). Jyot cannot recover locally stored videos if they are lost due to clearing browser data, uninstalling the app, switching devices, using a different browser profile, or device reset. It is your responsibility to maintain backups of any content that is important to you.</p>
          </section>

          <section>
            <h2 className="text-lg font-serif text-stone-900 mb-2">10. Termination</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>You may delete your account at any time from Profile → Delete Account.</li>
              <li>We reserve the right to suspend or terminate accounts that violate these terms, engage in prohibited conduct, or are inactive for an extended period.</li>
              <li>Upon termination, your access to the application ceases. Server-side data is deleted in accordance with our Privacy Policy.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-serif text-stone-900 mb-2">11. Changes to Terms</h2>
            <p>We may update these Terms &amp; Conditions from time to time. Significant changes will be notified through the app or via the email address associated with your account. Continued use of Jyot after changes constitutes acceptance of the updated terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-serif text-stone-900 mb-2">12. Governing Law</h2>
            <p>These terms are governed by the laws of India. Any disputes arising out of or relating to these terms shall be subject to the jurisdiction of the courts in Delhi, India.</p>
          </section>

          <section>
            <h2 className="text-lg font-serif text-stone-900 mb-2">13. Contact</h2>
            <p>For questions about these terms, please contact us at:</p>
            <p className="mt-1 font-medium text-amber-800">parththukral16@gmail.com</p>
          </section>

        </div>

        <div className="mt-8 pt-6 border-t border-amber-200 space-y-3">
          <Link to="/privacy-policy" className="w-full inline-block text-center py-3 rounded-xl border border-amber-200 text-stone-700 font-medium text-sm hover:bg-amber-50 transition-colors">
            View Privacy Policy
          </Link>
          <Link to="/" className="w-full inline-block text-center py-3 rounded-xl bg-stone-950 text-amber-50 font-medium text-sm hover:bg-stone-800 transition-colors">
            Return to Jyot
          </Link>
        </div>
      </div>
    </div>
  );
}
